# Generated by Django 4.1.2 on 2022-10-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
