# Generated by Django 4.0.6 on 2022-10-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuapp', '0004_mypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mypage',
        ),
    ]
