# Generated by Django 4.0.6 on 2022-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuapp', '0005_delete_mypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brithday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
