# Generated by Django 4.1.1 on 2022-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
