# Generated by Django 4.1.1 on 2022-09-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0003_remove_cashbook_updated_at_alter_cashbook_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='created_at',
        ),
    ]
