# Generated by Django 4.0.6 on 2022-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0005_cashbook_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='writer',
            field=models.TextField(default='천우', max_length=20),
        ),
    ]
