# Generated by Django 4.0.6 on 2022-09-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0006_alter_cashbook_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='writer',
        ),
        migrations.AddField(
            model_name='cashbook',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
