# Generated by Django 4.0.6 on 2022-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0007_remove_cashbook_writer_cashbook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='writer',
            field=models.TextField(default='천우', max_length=20),
        ),
    ]
