# Generated by Django 4.0.6 on 2022-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0009_remove_cashbook_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
