# Generated by Django 4.0.6 on 2022-09-25 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0010_cashbook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
